version: '3'

services:
  api-ddd-ca:
    image: enzor/api-ddd-clean_architecture
    ports: 
      - 3333:3333
  api-ddd-ca-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apidddca